import type { Metadata } from "next";
import { DEFAULT_LOCALE, LOCALES, localeHref, type Locale } from "./i18n";

export const SITE_URL = "https://dizegnoagency.com";
export const SITE_NAME = "Dizegno";

// Default share image, generated by src/app/api/og/route.tsx. Lives under
// /api/ so the locale rewrite in proxy.ts leaves the URL alone.
export const OG_IMAGE = { url: "/api/og/", width: 1200, height: 630 } as const;

export const OG_LOCALE: Record<Locale, string> = { ru: "ru_RU", en: "en_US", uz: "uz_UZ" };

// Dictionary strings arrive with non-breaking spaces from preventOrphans;
// <meta> content and JSON-LD want ordinary spaces.
export function plainText(text: string): string {
  return text.replace(/ /g, " ");
}

export function absoluteUrl(path: string): string {
  return new URL(path, SITE_URL).toString();
}

// Trims a description to what search engines actually show, on a word boundary.
export function truncate(text: string, max = 155): string {
  const clean = plainText(text).replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  return `${clean.slice(0, max).replace(/[\s,;:—-]+\S*$/, "")}…`;
}

// hreflang set for an unprefixed path ("/work/"): every locale plus
// x-default pointing at the unprefixed Russian version.
export function languageAlternates(path: string): Record<string, string> {
  return {
    ...Object.fromEntries(LOCALES.map((locale) => [locale, absoluteUrl(localeHref(locale, path))])),
    "x-default": absoluteUrl(localeHref(DEFAULT_LOCALE, path)),
  };
}

type PageMeta = {
  lang: Locale;
  // Unprefixed path, e.g. "/work/" — the locale prefix is added here.
  path: string;
  title: string;
  description: string;
  // The home page carries the full brand title and skips the "— Dizegno" template.
  absoluteTitle?: boolean;
  image?: { url: string; width?: number; height?: number; alt?: string };
};

// One place that knows how title, description, canonical, hreflang and the
// share card fit together, so every public page emits the same shape.
export function pageMetadata({ lang, path, title, description, absoluteTitle, image }: PageMeta): Metadata {
  const url = absoluteUrl(localeHref(lang, path));
  const cleanTitle = plainText(title);
  const cleanDescription = plainText(description);
  const shareImage = image ?? { ...OG_IMAGE, alt: SITE_NAME };

  return {
    title: absoluteTitle ? { absolute: cleanTitle } : cleanTitle,
    description: cleanDescription,
    alternates: { canonical: url, languages: languageAlternates(path) },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: OG_LOCALE[lang],
      url,
      title: cleanTitle,
      description: cleanDescription,
      images: [shareImage],
    },
    twitter: {
      card: "summary_large_image",
      title: cleanTitle,
      description: cleanDescription,
      images: [shareImage.url],
    },
  };
}
